#!/usr/bin/env python3
"""把编译好的 SPIR-V 嵌入为 C++ 头(避免运行期文件路径依赖)。

用法: embed_shaders.py <vert.spv> <frag.spv> <out.h>
生成 uint32_t 数组,与 vkCreateShaderModule 的 pCode 直接兼容。
"""
import sys


def words(path):
    with open(path, "rb") as f:
        data = f.read()
    assert len(data) % 4 == 0, f"{path} 不是合法的 SPIR-V(长度非 4 的倍数)"
    out = []
    for i in range(0, len(data), 4):
        v = data[i] | (data[i + 1] << 8) | (data[i + 2] << 16) | (data[i + 3] << 24)
        out.append(f"0x{v:08x}")
    return out


def emit(f, name, arr):
    f.write(f"inline const std::array<uint32_t, {len(arr)}> {name} = {{\n")
    for i in range(0, len(arr), 8):
        f.write("  " + ", ".join(arr[i:i + 8]) + ",\n")
    f.write("};\n")


def main():
    vert, frag, out = sys.argv[1], sys.argv[2], sys.argv[3]
    vw = words(vert)
    fw = words(frag)
    with open(out, "w") as f:
        f.write("// Generated by embed_shaders.py; do not edit.\n")
        f.write("#pragma once\n#include <cstdint>\n#include <array>\n")
        emit(f, "kStrokeVertSpv", vw)
        emit(f, "kStrokeFragSpv", fw)
    return 0


if __name__ == "__main__":
    sys.exit(main())
